const WeatherActionTypes = {
	FETCH_WEATHER_START: 'FETCH_WEATHER_START',
	FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
	FETCH_WEATHER_FAILED: 'FETCH_WEATHER_FAILED',
};

export default {
	...WeatherActionTypes,
};